BPMS-2/BPMS-2/Controllers/BikeReturnController.cs
using BPMS_2.Data;
using BPMS_2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BPMS_2.Controllers
{
	[Authorize]
    public class BikeReturnController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly BPMS_2Context _context;
        private readonly ILogger<AccountController> _logger;
        public BikeReturnController(BPMS_2Context context, UserManager<IdentityUser> userManager, ILogger<AccountController> logger)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<string> GetCurrentUserId()
        {
            IdentityUser usr = await GetCurrentUserAsync();
            return usr?.UserName;
        }

        private Task<IdentityUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IActionResult> Index()
        {
            var UID = await GetCurrentUserId();
            var orderdetails = from orderdetail in _context.OrderDetailsModel
                               where orderdetail.UID == UID
                               where orderdetail.Returned == false
                               where orderdetail.ProductCategory == "Rent"
                               select orderdetail;


            return View(orderdetails);

        }

     
        public OrderDetailsModel GetProductById(Guid productId)
        {

            return _context.OrderDetailsModel.FirstOrDefault(p => p.ProductId == productId && p.Returned==false);

        }


        [HttpPost("{productId}/BikeReturn")]
        public async Task<IActionResult> Return(Guid productId)
        {
           
            var order = GetProductById(productId);
            if(order.ReturnDate>=DateTime.UtcNow)
            {
                ViewBag.message = 0;
              
            }
            else
            {
                var diff = (DateTime.UtcNow - order.ReturnDate).Days;
                decimal fineMoney = diff * 10;
                ViewBag.message=fineMoney.ToString();
            }
            

            order.Returned = true;
            await _context.SaveChangesAsync();

            string message = $"Bike returned by {await GetCurrentUserId()}";
            _logger.LogInformation(message);
            return View();

        }
    }
}

BPMS-2/BPMS-2/Controllers/CartController.cs
using BPMS_2.Data;
using BPMS_2.Models;
using LearnASPNETCoreMVCWithRealApps.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BPMS_2.Controllers
{
    public class CartController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly BPMS_2Context _context;
        public CartController(BPMS_2Context context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ProductsModel.ToListAsync());
        }


        public IActionResult Failure()
        {
            return View();
        }

        [Authorize]
        public IActionResult FinalCart()
        {
            var cart = SessionHelper.GetObjectFromJson<List<OrderDetailsModel>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.TotalPrice);
            //ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
            return View();
        }   

        public ProductsModel GetProductById(Guid productId)
        {
            return _context.ProductsModel.SingleOrDefault(p => p.ProductId == productId);
        }



        public async Task<string> GetCurrentUserId()
        {
            IdentityUser usr = await GetCurrentUserAsync();
            return usr?.UserName;
        }

        private Task<IdentityUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        [Authorize]
        [HttpPost("{productId}")]
        public async Task<IActionResult> AddOrder(Guid productId, int quantity)
        {
            var product = GetProductById(productId);
            if (SessionHelper.GetObjectFromJson<List<OrderDetailsModel>>(HttpContext.Session, "cart") == null)
            {
                List<OrderDetailsModel> cart = new List<OrderDetailsModel>();
                if(quantity<=product.InventoryCount)
                {
                    cart.Add(new OrderDetailsModel
                    {

                        Quantity = quantity,
                        ProductId = productId,
                        ProductPrice = product.ProductPrice,
                        ProductCategory = product.ProductCategory,
                        Returned = false,
                        UID=await GetCurrentUserId(),
                        BikesPartsImage=product.BikePartImage


                    });
                    product.InventoryCount -= quantity;
                    
                    await _context.SaveChangesAsync();
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                    return RedirectToAction("FinalCart");

                }
                else
                {
                    return View("Failure");
                }
                
            }

            else
            {
                List<OrderDetailsModel> cart = SessionHelper.GetObjectFromJson<List<OrderDetailsModel>>(HttpContext.Session, "cart");
                int index = isExist(productId);
                if (index != -1 && product.InventoryCount >= quantity)
                {
                    cart[index].Quantity+=quantity;
                    product.InventoryCount -= quantity;

                    await _context.SaveChangesAsync();
                }
                else
                {
                    if(product.InventoryCount>=quantity)
                    {
                        cart.Add(new OrderDetailsModel
                        {
                            Quantity = quantity,
                            ProductId = productId,
                            ProductPrice = product.ProductPrice,
                            ProductCategory=product.ProductCategory,
                            Returned=false,
                            UID = await GetCurrentUserId(),
                            BikesPartsImage = product.BikePartImage

                        });
                        product.InventoryCount -= quantity;

                        await _context.SaveChangesAsync();

                    }
                    
                }

                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                return RedirectToAction("FinalCart");
            }

            
        }


        

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Remove(Guid productId)
        {
            List<OrderDetailsModel> cart = SessionHelper.GetObjectFromJson<List<OrderDetailsModel>>(HttpContext.Session, "cart");
            int index = isExist(productId);
            
            var product = GetProductById(productId);
            product.InventoryCount += cart[index].Quantity;

            cart.RemoveAt(index);

            await _context.SaveChangesAsync();

            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("FinalCart");
        }


        private int isExist(Guid productId)
        {
            List<OrderDetailsModel> cart = SessionHelper.GetObjectFromJson<List<OrderDetailsModel>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].ProductId.Equals(productId))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

        /* 
            cart.OrderDetails.Add(orderDetail);

            _context.OrderDetailsModel.Add(orderDetail);

            await _context.SaveChangesAsync();



            return RedirectToAction("Index1");
            */

       // public async Task<IActionResult> Index1()
        //{
          //  return View();
        //}

BPMS-2/BPMS-2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BPMS_2.Data;
using BPMS_2.Models;
using Microsoft.AspNetCore.Authorization;

namespace BPMS_2.Controllers
{
    public class ProductsController : Controller
    {
        private readonly BPMS_2Context _context;
        private readonly ILogger<AccountController> _logger;

        public ProductsController(BPMS_2Context context, ILogger<AccountController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProductsModel.ToListAsync());
        }

        // GET: Products/Details/5
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.ProductsModel == null)
            {
                return NotFound();
            }

            var productsModel = await _context.ProductsModel
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (productsModel == null)
            {
                return NotFound();
            }

            return View(productsModel);
        }

        // GET: Products/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ProductId,ProductCategory,ProductDescription,ProductSize,InventoryCount,ProductPrice,BikePartImage")] ProductsModel productsModel)
        {
            if (ModelState.IsValid)
            {
                productsModel.ProductId = Guid.NewGuid();
                _context.Add(productsModel);
                await _context.SaveChangesAsync();
                string message = $"Product added in products database. Product ID - {productsModel.ProductId}.";
                _logger.LogInformation(message);
                return RedirectToAction(nameof(Index));
            }
            return View(productsModel);

        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.ProductsModel == null)
            {
                return NotFound();
            }

            var productsModel = await _context.ProductsModel.FindAsync(id);
            if (productsModel == null)
            {
                return NotFound();
            }
            return View(productsModel);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProductId,ProductCategory,ProductDescription,ProductSize,InventoryCount,ProductPrice,BikePartImage")] ProductsModel productsModel)
        {
            if (id != productsModel.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productsModel);
                    await _context.SaveChangesAsync();
                    string message = $"Products database updated. Product ID - {productsModel.ProductId}.";
                    _logger.LogInformation(message);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsModelExists(productsModel.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productsModel);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.ProductsModel == null)
            {
                return NotFound();
            }

            var productsModel = await _context.ProductsModel
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (productsModel == null)
            {
                return NotFound();
            }

            return View(productsModel);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.ProductsModel == null)
            {
                return Problem("Entity set 'BPMS_2Context.ProductsModel'  is null.");
            }
            var productsModel = await _context.ProductsModel.FindAsync(id);
            if (productsModel != null)
            {
                _context.ProductsModel.Remove(productsModel);
                string message = $"Product removed from products database. Product ID - {productsModel.ProductId}.";
                _logger.LogInformation(message);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsModelExists(Guid id)
        {
          return _context.ProductsModel.Any(e => e.ProductId == id);
        }
    }
}

BPMS-2/BPMS-2/Controllers/SalesController.cs
using BPMS_2.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BPMS_2.Controllers
{
    public class SalesController : Controller
    {

        private readonly BPMS_2Context _context;
        private readonly UserManager<IdentityUser> _userManager;
        
        public SalesController(BPMS_2Context context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }



        public async Task<string> GetCurrentUserId()
        {
            IdentityUser usr = await GetCurrentUserAsync();
            return usr?.UserName;
        }

        private Task<IdentityUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);


        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.CartModel.ToListAsync());
        }


        public async Task<IActionResult> UserRecord()
        {
            var UID = await GetCurrentUserId();
            var records=from record in _context.CartModel
                      where record.UID == UID
                      select record;

            return View(records);
        }
    }
}

BPMS-2/BPMS-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BPMS_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BPMS_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BPMS_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <button class="pushable">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        </button>
                        <button class="pushable">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rent" asp-action="Index">Rent Bikes</a>
                        </li>
                        </button>
                        <button class="pushable">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Buy Parts and Bikes</a>
                        </li>
                        </button>
                        <button class="pushable">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="UserRecord">Order History</a>
                        </li>
                        </button>
                        <button class="pushable">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BikeReturn" asp-action="Index">Return Bike</a>
                        </li>
                        </button>

                        @if(User.IsInRole("Admin"))
                        {
                            
                        <button class="pushable">
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Manage Products</a>
                        </li>
                        </button>
                            <button class="pushable">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RentBikesModels" asp-action="Index">Manage Rental Bikes</a>
                        </li>
                        </button>
                        <button class="pushable">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Sales</a>
                        </li>
                        </button>
  
                        }
                        
                        


                        </div>
                        <partial name="_LoginPartial" />
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BPMS_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>